title: Titahi Bay Labs
description: Researching safe and beneficial AI systems
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Titahi Bay Labs
